### ISSUE TITLE
xdebug_break not working on drupal 8.6.10

### ISSUE THREAD

**Issue by liaogz82** [tacnoman/dephpugger#33]
I can't run xdebug on drupal. it just skip the command `xdebug_break();`

```
root@64107e503f33:/var/www/html# vendor/bin/dephpugger requirements

Checking your dependencies

  ✔️ Your PHP version is 7.0 or more
  ✔️ XDebug is installed.
  ✔️ Sockets extension is installed.
  ✔️ XDebug is active.

 -- Infos about PHP environment --

XDebug idekey: no value => no value
XDebug cli_color: 0 => 0
XDebug default_enable: On => On
root@64107e503f33:/var/www/html# vendor/bin/dephpugger info

Checking your dependencies

  ✔️ XDebug is installed.
  ✔️ XDebug is active.

 -- Infos about PHP environment --

xdebug.auto_trace: auto_trace
xdebug.collect_assignments: collect_assignments
xdebug.collect_params: collect_params
xdebug.collect_vars: collect_vars
xdebug.default_enable: default_enable
xdebug.dump_globals: dump_globals
xdebug.dump_undefined: dump_undefined
xdebug.file_link_format: file_link_format
xdebug.force_display_errors: force_display_errors
xdebug.gc_stats_enable: gc_stats_enable
xdebug.gc_stats_output_name: gc_stats_output_name
xdebug.idekey: idekey
xdebug.max_stack_frames: max_stack_frames
xdebug.profiler_aggregate: profiler_aggregate
xdebug.profiler_enable: profiler_enable
xdebug.profiler_enable_trigger_value: profiler_enable_trigger_value
xdebug.profiler_output_name: profiler_output_name
xdebug.remote_autostart: remote_autostart
xdebug.remote_cookie_expire_time: remote_cookie_expire_time
xdebug.remote_handler: remote_handler
xdebug.remote_log: remote_log
xdebug.remote_port: remote_port
xdebug.scream: scream
xdebug.show_exception_trace: show_exception_trace
xdebug.show_mem_delta: show_mem_delta
xdebug.trace_enable_trigger_value: trace_enable_trigger_value
xdebug.trace_options: trace_options
xdebug.trace_output_name: trace_output_name
xdebug.var_display_max_data: var_display_max_data
```

This is the dockerfile I use

```
FROM drupal:8.6.10-apache

RUN pecl update-channels; \
  pecl install xdebug; \
  docker-php-ext-enable xdebug; \
  docker-php-ext-install sockets; \
  apt autoremove -y apache2;

RUN rm -rf /tmp/pear ~/.pearrc

CMD ["php", "vendor/bin/dephpugger", "server"]
```

The version of the dephpugger i use is 1.5.0. Please look into it. Thanks

**Comment by slothyrulez** [comment]
Same situation here, comming from https://medium.com/@mosesliao/debug-drupal-using-dephpugger-a0839f878b56
